### ISSUE TITLE
Wallet Broken

### ISSUE THREAD

**Issue by Kakiharu** [BeardlessBrady/Currency-Mod#109]
When you have a bunch of different currency in your wallet and you put it into the shop it doesn't subtract the money from the wallet.

**Comment by jbjornberg** [comment]
How to replicate:
Make item 65$
- Have Currency of all kinds in your wallet (ideally equivalent amounts)
- Make sure the total of the currency held in your wallet is 65$ with a little bit of change.

If you have 66$+ it’ll work as intended, but if you have 65.48, 65.93 etc.— it’ll only subtract a 1/3rd of the price.

Basically,
Have the exact amount + a little extra in all forms of currency to get a 1/3 discount on everything in the store.

**Comment by Tanguygab** [comment]
Hey, I just want to let you know that the v1 of the mod isn't really supported anymore, and that this issue will probably necer get fixed for this version (Brady already tried to get into v1's code one time and just couldn't) Since v2 is a complete rewrite, the wallet will probably be made another way and more efficient (and probably without this bug =) )

**Comment by Beardlessbrady** [comment]
Unfortunately I am only supporting the 2.0 version. Sorry
