### ISSUE TITLE
April 30th ALPHA - Vending/Trade-In Machine GUI Sync requires re-connect

### ISSUE THREAD

**Issue by SlendyMcTendies** [BeardlessBrady/Currency-Mod#114]
The Vending/Trade-In machines in the April 30th ALPHA release requires players to re-connect to the server in order to see if a transaction has taken place. Stock, Remaining Funds, and Profit values will NOT change otherwise.

Additionally, while in a non-synced state, there have been instances of items getting lost to the void when attempting to take them out of a Trade-In machine but it's inconsistent (and I personally believe to be a result of the de-sync).

To clarify: I set up Vending/Trade-In machine. Other player performs a transaction. I don't see results unless I re-connect.

**Comment by Tanguygab** [comment]
those have been fixed in the dev-builds on the discord server if I remember correctly =)
Direct link: https://cdn.discordapp.com/attachments/518558094675148807/705323686219087912/Currency-1.12.0-2.0.0-ALPHA-20200430.jar
Test it if you still have the problems
NOTE: The mod's ID have been changed from modcurrency to modcurrency2 which means that all blocks and items IDs have been changed.

**Comment by SlendyMcTendies** [comment]
That build you linked is the exact one I'm using and the issue persists. It's not an issue when you personally use them, as all client-side data functions. This issue specifically relates to multiplayer when another player uses the machine. I've messaged BeardlessBrady about it.

If you look at the file name, you'll notice it reads "[...]-20200430" That's April 30th 2020

**Comment by Beardlessbrady** [comment]
I can reproduce this one. I will work on a fix. Thank you!
