### ISSUE TITLE
[brainstorming ideas] Great mod!

### ISSUE THREAD

**Issue by winsrp** [BeardlessBrady/Currency-Mod#2]
just tried this and is so much f awesome lol.

Some ideas I have about this:

Change recipe of the vending machine to use a comparator instead of a repeater, makes more sense =D

I would change the numbers on the bills image and replace images as what you did with the current 100$ bill, the bills are still named 1, 5, 10 etc, so it would be:

-wood bill  = 1
-stone bill  = 5
-coal bill  = 10
-iron bill = 20
-lapiz bill = 50
-redstone = 100
-quartz = 1.000
-gold bill = 10.000
-diamond bill = 100.000
-emerald bill = 1.000.000

put in the background whatever color you like to make it look cool, maybe a contrasting color. This way denominations is high, math is better, and you don't end up with stacks over stacks of 100$ bills, lol =D

And you could also have in the middle any other special bills, the creeper bill = 2.000, the zombie bill = 5.000, the skeleton bill = 20.000, you name it, mix and match as you like! images are better than numbers on bills, you can have more variety.

In regards of the vending machine interface, it seems great, but the middle mouse button click is kind of weird to select stuff, I'll change it in the following way: 
-If you click the items on the vending machine, item interaction is as normal
-if you click the slot settings tab the interface will change to selection mode, so that when you do a left click you have that items selected and you can input it's price.
-clicking the slot setting tab again will deselect everything and return to normal mode.

Also how about a console message when you shift right click to change the mode of your vending machine, extra info is always good, or you could change the front texture to have like a red button that turns green or something more visual (text is easier) =D

What is the lock option for?, maybe it could have some information about it written on it when you either click to set or click to remove.

In regards of currency distribution, I would either leave that to server admins, or as I saw in your planned features, make the exchange machine (in lack of a better name), where the interface is like the vending machine but it works the other way around, when you click with an item on the machine slot, the item is not taken but only the image of the item is set in place, and the same rules features to set price work as above, I would also keep the infinite option for admin machines, and all the sudden with admin selling machines you have currency flowing!, 

Also I saw that you have planned an ATM machine, I would not do this as this would make sense if you also had something like debit cards, where you deposit the money and put it into your card, but something like that effectively would kill the bills, as you could leave only the debit card with the total balance and use in on machines and be done with it, and it would make it more simple to be honest, but less nice. But since this is minecraft and I saw you want to make a wallet, but instead of a wallet it could be a hybrid between a wallet and a debit card, lets call it a wallet card!, where you can use it in the atm to get money in and out, but cannot use it in the machines!

Sorry for the amount of info, but I just loved this mod

**Comment by winsrp** [comment]
The ATM maybe is like a money transfer machine, more than ATM.. this way users can craft their wallet cards, and store money on them, and the exchange machine is the preferred distribution method! Also with a OP/creative mode, where admins can just fill wallet cards, for specific server awards!

**Comment by Beardlessbrady** [comment]
Alright I will respond to each part individually

1) Recipe change: I can do that if it makes more sense 
2) Bill change: I quite like my bills currently and adding more larger ones like 1,000 10,000 etc would just make the smaller ones worth less and people would probably make their prices higher
3)Selection change: I can probably implement this, should work.
4) Console message/indication of mode change: I personally hate chat messages. I do plan on animating the vending machine door to open when in edit mode I just haven't gotten to it yet but its still planned!
5)Lock: As stated on the curse page this mod is in beta and I'm sloppy and sometimes leave half finished features in when I release versions, it'll have a use soon. 
6) The Exchange machine (Might steal that name for it) is coming next release. I haven't had too much time to work on it because exam season.
7) I agree completely with the atm, I will not be adding debit cards. It was requested by a few people. Basically you can insert money into it for storage or pull money out of it. The thing is your balance is the same for any ATM so its like a universal storage of your money


your 2nd message is spot just about what Im planning to do. 
Also the wallet will just be a place to keep your bills (but will only stack to a certain amount).
It will make things much easier in the vending machine because instead of throwing money into it you will just have to put the wallet into the money slot. Not sure if I explained that very well

Anywho thank you so much for the feedback, I'm glad you enjoy my mod to the point where you want to give me this much detail. I have so much planned for this mod and it's no where near where I want it

If you have any other suggestions feel free to drop me a PM

**Comment by winsrp** [comment]
1. Thinking a little bit more about, maybe you could do a vending circuit item, and a exchange circuit item, that could be used in the place where you have now the repeater, and depending on the circuit you use you craft one item or the other (since vending and exchange are the same thing just opposite logic), and those circuits are just a weird combo or a repeater, comparator, redstone, might be cool, for the 3x3 crafting grid.

2. The thing is that many other mods add tons of minerals and materials in the middle or above of what normal items are valued, so I can see the use for bigger currencies, e.g. dirt is like price 1... and something like a diamond could be 5.000 of value, so that would require 50 x 100$ bills, and for example a diamond sword with many enchantments could be way over 50.000 just to name some number out of the top of my head so, that would be 500x 100$ bills... not to mention something like tinkers construct items that add a ton of stuff, those could be really expensive, even with the wallet I can see issues there.

3. Door that opens!! COOL!, 

4. The name is as good as yours! go ahead!

5. I would stay away of the ATMs and work with the wallet and bigger bills instead, less of a hassle for you program wise, and less of a problem for server admins if the server money info ever gets corrupted with a bug or something, 

6. U know what, I'll add one more, and add the money safe item, a working safe that you can put a password on to open (have you tried malisis doors mod?, check that one out, you can make a custom door with a password on it, same idea but with a safe item!, or you could say it's biometric and only the owner can open it =P, essentially a secure chest! want to make it extra secure, no one can break it except OPs or the owner. now that is a way to keep your money safe!, put all the chase of wallets you have in it, and maybe some diamonds, already love the idea, hahaha!

So going back a sec here, the way you are going to do the wallets is something like the iron backpack mods, (essentially an item that opens like a chest while in hand) but the only items you can store are money bills items?, so you can have let say like a small chest 9x3 slots that you can fill with stacks of 64 say 100$ bills, for a total of 172.800 per wallet? can they be upgraded? so first is leather wallet, iron wallet, gold wallet, diamond wallet? maybe you can start with a smaller grid, with like 3x3 and work you way up to a double chest like with upgrades, for a total of 345,600 as max? if that is the case ~345k might still be a little low, also it will still work as debit card that you can put it into machines and get charged from there?

**Comment by winsrp** [comment]
Hmm... more ideas come to my head, lol

7. how about something that makes experience to money and money to experience! monetize experience!, the Monitizer!, good way to make money, good way to make experience, and good way to store experience all in one.

8. again with wallets, put it in an anvil and be able to name your wallet!

9. shit I had another idea and lost it... when I remember I'll put it.
